### ISSUE TITLE
Missing step not described

### ISSUE THREAD

**Issue by cmoulliard** [christian-posta/ceposta-devops-ose#3]
The doc does not refer (like the second video) after downloading the docker images & starting the different servers hosted by docker (jenkins, nexus, gerrit, gitlab) how to install/important some projects within gitlab.

I have also discovered that gitlab web server is requesting to have an account when we connect to the web site the first site. Of course, we don't receive any confirmation email after the registration on the local web site

**Comment by cmoulliard** [comment]
This step is described as manual step

**Comment by christian-posta** [comment]
the docs here describe those steps: https://github.com/christian-posta/ceposta-devops-ose/blob/master/docs/set-up-gitlab.md
